-- JOB_INFO 테이블 생성
CREATE TABLE JOB_INFO(
    JOB_ID           VARCHAR(10),   -- 직업 아이디
    MIN_SALARY   NUMBER,         -- 최저급여
    MAX_SALARY  NUMBER          -- 최고급여
);

INSERT INTO JOB_INFO(JOB_ID, MIN_SALARY, MAX_SALARY)
VALUES('AD_PRES', 20000, 40000);
INSERT INTO JOB_INFO(JOB_ID, MIN_SALARY, MAX_SALARY)
VALUES('AD_VP', 15000, 30000);
INSERT INTO JOB_INFO(JOB_ID, MIN_SALARY, MAX_SALARY)
VALUES('AD_ASST', 3000, 6000);
INSERT INTO JOB_INFO(JOB_ID, MIN_SALARY, MAX_SALARY)
VALUES('FI_MGR', 8000, 16000);
INSERT INTO JOB_INFO(JOB_ID, MIN_SALARY, MAX_SALARY)
VALUES('FI_ACCOUNT', 4000, 9000);
INSERT INTO JOB_INFO(JOB_ID, MIN_SALARY, MAX_SALARY)
VALUES('AC_MGR', 8000, 16000);
INSERT INTO JOB_INFO(JOB_ID, MIN_SALARY, MAX_SALARY)
VALUES('AC_ACCOUNT', 4000, 9000);

SELECT * FROM JOB_INFO;

-- 최저급여의 평균을 구하시오
SELECT ROUND(AVG(MIN_SALARY), -1) 최저급여평균, AVG(MAX_SALARY) 최고급여평균 FROM JOB_INFO;

-- 최저급여가 5000달러 이상인 직업 아이디를 검색하시오
-- 코딩순서 = 1. FROM절 -> 2. WHERE절 -> 3. SELECT -> 4, 정렬
SELECT JOB_ID 직업아이디, MIN_SALARY 최저급여
FROM JOB_INFO
WHERE MIN_SALARY >= 5000;
      -- MIN_SALARY 별칭 WHERE에서 사용 불가 = 코딩 순서때문

-- 최저 급여가 5000달러 이상인 정보를 검색한 뷰 생성
CREATE VIEW V_JOB_INFO
AS SELECT *
    FROM JOB_INFO
    WHERE MIN_SALARY >= 5000;
    
SELECT * FROM V_JOB_INFO;

-- 최고급여와 최저 급여의 차가 10000달러 이상인 직업아이디 수
SELECT COUNT(*) 직업아이디수 FROM V_JOB_INFO
WHERE MAX_SALARY - MIN_SALARY >= 10000;

SELECT JOB_ID 
FROM V_JOB_INFO
WHERE MAX_SALARY - MIN_SALARY >= 10000;

-- 직업 아이디의 이름이 FI로 시작하는 자료를 검색하시오
SELECT JOB_ID FROM V_JOB_INFO
WHERE JOB_ID LIKE 'FI%';

-- MAX_SALARY가 최고인 직업 아이디를 검색하시오
SELECT MAX(MAX_SALARY) FROM V_JOB_INFO;

SELECT V_JOB_INFO.JOB_ID, V_JOB_INFO.MAX_SALARY
FROM V_JOB_INFO
WHERE MAX_SALARY = (SELECT MAX(MAX_SALARY) FROM V_JOB_INFO);

-- MIN_SALARY가 최저인 직업 아이디를 검색하시오
SELECT MIN(MIN_SALARY) 최저급여 FROM V_JOB_INFO;

SELECT V_JOB_INFO.JOB_ID, V_JOB_INFO.MAX_SALARY
FROM V_JOB_INFO
WHERE MIN_SALARY = (SELECT MIN(MIN_SALARY) FROM V_JOB_INFO);

SELECT V_JOB_INFO.JOB_ID, V_JOB_INFO.MAX_SALARY
FROM V_JOB_INFO
WHERE MAX_SALARY = (SELECT MAX(MAX_SALARY) FROM V_JOB_INFO)
     OR MIN_SALARY = (SELECT MIN(MIN_SALARY) FROM V_JOB_INFO);





COMMIT;

DROP TABLE JOB_INFO;
DROP VIEW V_JOB_INFO;