-- JOB_INFO 테이블 생성
CREATE TABLE JOB_INFO(
    JOB_ID           VARCHAR(10),   -- 직업 아이디
    MIN_SALARY   NUMBER,         -- 최저급여
    MAX_SALARY  NUMBER          -- 최고급여
);

INSERT INTO JOB_INFO(JOB_ID, MIN_SALARY, MAX_SALARY)
VALUES('AD_PRES', 20000, 40000);
INSERT INTO JOB_INFO(JOB_ID, MIN_SALARY, MAX_SALARY)
VALUES('AD_VP', 15000, 30000);
INSERT INTO JOB_INFO(JOB_ID, MIN_SALARY, MAX_SALARY)
VALUES('AD_ASST', 3000, 6000);
INSERT INTO JOB_INFO(JOB_ID, MIN_SALARY, MAX_SALARY)
VALUES('FI_MGR', 8000, 16000);
INSERT INTO JOB_INFO(JOB_ID, MIN_SALARY, MAX_SALARY)
VALUES('FI_ACCOUNT', 4000, 9000);
INSERT INTO JOB_INFO(JOB_ID, MIN_SALARY, MAX_SALARY)
VALUES('AC_MGR', 8000, 16000);
INSERT INTO JOB_INFO(JOB_ID, MIN_SALARY, MAX_SALARY)
VALUES('AC_ACCOUNT', 4000, 9000);

SELECT * FROM JOB_INFO;


COMMIT;

DROP TABLE JOB_INFO;